
name: binder-base
dependencies:
- jupyter
- matplotlib>=2
- geopandas>=0.3
- numpy>=1.1
- pandas>=0.23
- numpy>=1.14
- shapely>=1.6

#- geopandas>=0.3.0
#- matplotlib>=2.2.3
#- numpy>=1.14.5
#- pandas>=0.23.4
#- numpy>=1.14.5
#- shapely>=1.6.4
